[tool.bumpversion]
current_version = "0.40.0-beta.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(-(?P<prerelease>(beta|rc))\\.(?P<prerelease_num>\\d+))?"
serialize = [
    "{major}.{minor}.{patch}-{prerelease}.{prerelease_num}",
    "{major}.{minor}.{patch}"
]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_files = false
ignore_missing_version = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Release version {new_version}"
allow_dirty = false
commit = false
message = "chore: bump version {current_version} â†’ {new_version}"

[tool.bumpversion.parts.prerelease]
optional_value = "stable"
values = ["beta", "rc", "stable"]

[tool.bumpversion.parts.prerelease_num]
first_value = "0"

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance = {{ version = "={current_version}"'
replace = 'lance = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-arrow = {{ version = "={current_version}"'
replace = 'lance-arrow = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-core = {{ version = "={current_version}"'
replace = 'lance-core = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-datafusion = {{ version = "={current_version}"'
replace = 'lance-datafusion = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-datagen = {{ version = "={current_version}"'
replace = 'lance-datagen = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-encoding = {{ version = "={current_version}"'
replace = 'lance-encoding = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-file = {{ version = "={current_version}"'
replace = 'lance-file = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-index = {{ version = "={current_version}"'
replace = 'lance-index = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-io = {{ version = "={current_version}"'
replace = 'lance-io = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-linalg = {{ version = "={current_version}"'
replace = 'lance-linalg = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-namespace = {{ version = "={current_version}"'
replace = 'lance-namespace = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-namespace-impls = {{ version = "={current_version}"'
replace = 'lance-namespace-impls = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-table = {{ version = "={current_version}"'
replace = 'lance-table = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-test-macros = {{ version = "={current_version}"'
replace = 'lance-test-macros = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-testing = {{ version = "={current_version}"'
replace = 'lance-testing = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'fsst = {{ version = "={current_version}"'
replace = 'fsst = {{ version = "={new_version}"'

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'lance-bitpacking = {{ version = "={current_version}"'
replace = 'lance-bitpacking = {{ version = "={new_version}"'

# Note: Individual rust crate Cargo.toml files use workspace = true,
# so we don't need to update them individually

# Python Cargo.toml
[[tool.bumpversion.files]]
filename = "python/Cargo.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

# Java lance-jni
[[tool.bumpversion.files]]
filename = "java/lance-jni/Cargo.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

# Java pom.xml
[[tool.bumpversion.files]]
filename = "java/pom.xml"
search = "<version>{current_version}</version>"
replace = "<version>{new_version}</version>"

