[default]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*spellchecker:disable-line$"]

[default.extend-words]
DNE = "DNE"
arange = "arange"
nd = "nd"
terrestial = "terrestial"
abd = "abd"
afe = "afe"
typ = "typ"
rabit = "rabit"
flate = "flate"

[default.expect]
nprobs = "nprobes"
nprob = "nprobe"

[files]
extend-exclude = ["notebooks/*.ipynb"]
# If a line ends with # or // and has spellchecker:disable-line, ignore it
