name: run-tests

description: "Install lance with uv and run integration tests"
runs:
  using: "composite"
  steps:
  - name: Sync environment
    working-directory: python
    shell: bash
    run: |
      set -euo pipefail
      uv sync --frozen --install-project --extra tests
  - name: Start localstack
    shell: bash
    run: |
      docker compose -f docker-compose.yml up -d --wait
  - name: Run python tests
    shell: bash
    working-directory: python
    run: make integtest
