[package]
name = "lance-index"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = "README.md"
description.workspace = "Lance indices implemnetation"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
arrow-array.workspace = true
arrow-ord.workspace = true
arrow-schema.workspace = true
arrow-select.workspace = true
arrow-arith.workspace = true
async-trait.workspace = true
futures.workspace = true
lance-arrow.workspace = true
lance-core.workspace = true
lance-linalg.workspace = true
num_cpus.workspace = true
rand.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
log.workspace = true

[dev-dependencies]
approx.workspace = true
