[workspace]
members = [
    "lance-arrow",
    "lance-linalg",
    "lance-testing",
    "lance",
]
# Python package needs to be built by maturin.
resolver = "2"

[workspace.package]
version = "0.7.4"
edition = "2021"
authors = ["Lance Devs <dev@lancedb.com>"]
license = "Apache-2.0"
repository = "https://github.com/lancedb/lance"

[workspace.dependencies]
# Note that this one does not include pyarrow
arrow = { version = "43.0.0", optional = false }
arrow-arith = "43.0"
arrow-array = "43.0"
arrow-buffer = "43.0"
arrow-cast = "43.0"
arrow-data = "43.0"
arrow-ipc = "43.0"
arrow-ord = "43.0"
arrow-row = "43.0"
arrow-schema = "43.0"
arrow-select = "43.0"
half = { "version" = "=2.2.1", default-features = false, features = [
    "num-traits"
] }
approx = "0.5.1"
criterion = { version = "0.5", features = ["async", "async_tokio"] }
log = "0.4"
num-traits = "0.2"
object_store = { version = "0.6.1", features = ["aws", "gcp", "azure"] }
pprof = { version = "0.12", features = ["flamegraph", "criterion"] }
rand = { version = "0.8.3", features = ["small_rng"] }
serde = { version = "^1" }
serde_json = { version = "1" }
snafu = "0.7.4"

[profile.bench]
opt-level = 3
debug = true
strip = false
