[package]
name = "lance"
version = "0.0.1-alpha0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/eto-ai/lance"
repository = "https://github.com/eto-ai/lance"
authors = ["Lance Developers <dev@eto.ai>"]
readme = "../README.md"
description = "Rust Implementation of Lance Columnar Format"

[[bin]]
name = "lance"

[lib]
crate-type=["staticlib", "cdylib", "lib"]

[dependencies]
arrow = { version = "20.0", default-features = false }
arrow2 = {version = "0.14.2", features = ["compute_arithmetics", "compute_take"]}
clap = { version = "3", features = ["derive"] }
prost = "0.11.0"
byteorder = "1.4"

[build-dependencies]
prost-build = { version = "0.11" }
