[package]
name = "lance"
version = "0.3.7"
edition = "2021"
authors = ["Lance Devs <dev@eto.ai>"]
description = "A columnar data format that is 100x faster than Parquet for random access."
license = "Apache-2.0"
repository = "https://github.com/eto-ai/lance"
readme = "README.md"
rust-version = "1.65"
keywords = [
    "data-format",
    "data-science",
    "machine-learning",
    "apache-arrow",
    "data-analytics"
]
categories = [
    "database-implementations",
    "data-structures",
    "development-tools",
    "science"
]

[dependencies]
bytes = "1.3"
arrow-arith = "32.0"
arrow-array = "32.0"
arrow-buffer = "32.0"
arrow-cast = "32.0.0"
arrow-data = "32.0"
arrow-ord = "32.0"
arrow-schema = "32.0"
arrow-select = "32.0"
async-recursion = "1.0"
async-trait = "0.1.60"
byteorder = "1.4.3"
chrono = "0.4.23"
clap = { version = "4.1.1", features = ["derive"], optional = true }
object_store = { version = "0.5.3", features = ["aws"] }
aws-config = "0.54"
aws-credential-types = "0.54.1"
pin-project = "1.0"
prost = "0.11"
prost-types = "0.11"
tokio = { version = "1.23", features = ["rt-multi-thread"] }
url = "2.3"
rand = { version = "0.8.3", features = ["small_rng"] }
futures = "0.3"
uuid = { version = "1.2", features = ["v4"] }
path-absolutize = "3.0.14"
arrow = { version = "32.0.0", features = ["prettyprint"] }
num_cpus = "1.0"
sqlparser = "0.30.0"
# TODO: use datafusion sub-modules to reduce build size?
datafusion = { version = "18.0.0", default-features = false }
faiss = { version = "0.11.0", features = ["gpu"], optional = true }

[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
clap = { version = "4.1.1", features = ["derive"] }
criterion = { version = "0.4", features = ["async", "async_tokio"] }
pprof = { version = "0.11", features = ["flamegraph", "criterion"] }
tempfile = "3.3.0"
approx = "0.5.1"

[features]
cli = ["clap"]

[[bin]]
name = "lq"
required-features = ["cli"]

[[bench]]
name = "distance"
harness = false

[[bench]]
name = "scan"
harness = false

[[bench]]
name = "vector_index"
harness = false

[[bench]]
name = "kmeans"
harness = false

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
