[package]
name = "lance"
version = "0.4.4"
edition = "2021"
authors = ["Lance Devs <dev@eto.ai>"]
description = "A columnar data format that is 100x faster than Parquet for random access."
license = "Apache-2.0"
repository = "https://github.com/eto-ai/lance"
readme = "README.md"
rust-version = "1.65"
keywords = [
    "data-format",
    "data-science",
    "machine-learning",
    "apache-arrow",
    "data-analytics"
]
categories = [
    "database-implementations",
    "data-structures",
    "development-tools",
    "science"
]

[dependencies]
bytes = "1.3"
arrow-arith = "33.0"
arrow-array = "33.0"
arrow-buffer = "33.0"
arrow-cast = "33.0.0"
arrow-data = "33.0"
arrow-ord = "33.0"
arrow-schema = "33.0"
arrow-select = "33.0"
async-recursion = "1.0"
async-trait = "0.1.60"
byteorder = "1.4.3"
chrono = "0.4.23"
clap = { version = "4.1.1", features = ["derive"], optional = true }
object_store = { version = "0.5.6", features = ["aws", "gcp"] }
reqwest = { version = "0.11.16" }
aws-config = "0.54"
aws-credential-types = "0.54.1"
pin-project = "1.0"
prost = "0.11"
prost-types = "0.11"
tokio = { version = "1.23", features = ["rt-multi-thread"] }
url = "2.3"
rand = { version = "0.8.3", features = ["small_rng"] }
futures = "0.3"
uuid = { version = "1.2", features = ["v4"] }
path-absolutize = "3.0.14"
shellexpand = "3.0.0"
arrow = { version = "33.0.0", features = ["prettyprint"] }
num_cpus = "1.0"
sqlparser-lance = "0.32.0"
# TODO: use datafusion sub-modules to reduce build size?
datafusion = { version = "19.0.0", default-features = false }
faiss = { version = "0.11.0", features = ["gpu"], optional = true }
lapack = "0.19.0"
cblas = "0.4.0"
lru_time_cache = "0.11"
num-traits = "0.2"
ordered-float = "3.6.0"

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = "0.3.2"

[target.'cfg(target_os = "linux")'.dependencies]
openblas-src = { version = "0.10.8", default-features= false, features = ["static", "cblas"]}

[target.'cfg(target_os = "linux")'.dev-dependencies]
pprof = { version = "0.11", features = ["flamegraph", "criterion"] }

[target.'cfg(target_os = "windows")'.dependencies]
openblas-src = { version = "0.10.8", default-features= false, features = ["system"]}

[target.'cfg(target_os="windows")'.build-dependencies]
vcpkg = "0.2"

[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
clap = { version = "4.1.1", features = ["derive"] }
criterion = { version = "0.4", features = ["async", "async_tokio"] }
tempfile = "3.3.0"
approx = "0.5.1"
dirs = "5.0.0"

[features]
cli = ["clap"]

[[bin]]
name = "lq"
required-features = ["cli"]

[[bench]]
name = "l2"
harness = false

[[bench]]
name = "scan"
harness = false

[[bench]]
name = "vector_index"
harness = false

[[bench]]
name = "kmeans"
harness = false

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
