[package]
name = "pylance"
version = "0.3.2"
edition = "2021"
authors = ["Lance Devs <dev@eto.ai>"]
rust-version = "1.65"

[lib]
name = "lance"
crate-type = ["cdylib"]

[dependencies]
arrow-array = "31.0"
arrow-data = "31.0"
arrow-schema = "31.0"
chrono = "0.4.23"
tokio = { version = "1.23", features = ["rt-multi-thread"] }
futures = "0.3"
pyo3 = { version = "0.17.3", features = ["extension-module", "abi3-py38"] }
arrow = { version = "31.0.0", features = ["pyarrow"] }

[target.'cfg(target_os = "macos")'.dependencies]
lance = { path = "../rust", features = ["blas"]}

[target.'cfg(not(target_os = "macos"))'.dependencies]
lance = { path = "../rust"}


[build-dependencies]
prost-build = "0.11"
