[package]
name = "pylance"
version = "0.4.17"
edition = "2021"
authors = ["Lance Devs <dev@eto.ai>"]
rust-version = "1.65"

[lib]
name = "lance"
crate-type = ["cdylib"]

[dependencies]
arrow-array = "37.0"
arrow-data = "37.0"
arrow-schema = "37.0"
chrono = "0.4.23"
tokio = { version = "1.23", features = ["rt-multi-thread"] }
futures = "0.3"
pyo3 = { version = "0.18.1", features = ["extension-module", "abi3-py38"] }
arrow = { version = "37.0.0", features = ["pyarrow"] }
lance = { path = "../rust"}
uuid = "1.3.0"
prost = "0.11"

[build-dependencies]
prost-build = "0.11"
