[package]
name = "pylance"
version = "0.8.8"
edition = "2021"
authors = ["Lance Devs <dev@lancedb.com>"]
rust-version = "1.65"
exclude = ["python/lance/conftest.py"]

[lib]
name = "lance"
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "47.0.0", features = ["pyarrow"] }
arrow-array = "47.0"
arrow-data = "47.0"
arrow-schema = "47.0"
async-trait = "0.1"
chrono = "0.4.31"
env_logger = "0.10"
futures = "0.3"
half = { version = "2.1", default-features = false, features = ["num-traits"] }
lance = { path = "../rust/lance", features = ["tensorflow", "dynamodb"] }
lance-arrow = { path = "../rust/lance-arrow" }
lance-core = { path = "../rust/lance-core" }
lance-index = { path = "../rust/lance-index" }
lance-linalg = { path = "../rust/lance-linalg" }
lazy_static = "1"
log = "0.4"
prost = "0.12"
pyo3 = { version = "0.19", features = ["extension-module", "abi3-py38"] }
tokio = { version = "1.23", features = ["rt-multi-thread"] }
uuid = "1.3.0"
serde_json = "1"
num_cpus = "1"
snafu = "0.7.4"
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.17"
tracing = "0.1.37"

[build-dependencies]
prost-build = "0.11"
