[package]
name = "pylance"
version = "0.7.4"
edition = "2021"
authors = ["Lance Devs <dev@lancedb.com>"]
rust-version = "1.65"
exclude = ["python/lance/conftest.py"]

[lib]
name = "lance"
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "43.0.0", features = ["pyarrow"] }
arrow-array = "43.0"
arrow-data = "43.0"
arrow-schema = "43.0"
async-trait = "0.1"
chrono = "0.4.23"
env_logger = "0.10"
futures = "0.3"
half = { version = "2.1", default-features = false, features = ["num-traits"] }
lance = { path = "../rust/lance", features = ["tensorflow", "dynamodb"] }
lazy_static = "1"
log = "0.4"
prost = "0.11"
pyo3 = { version = "0.19", features = ["extension-module", "abi3-py38"] }
tokio = { version = "1.23", features = ["rt-multi-thread"] }
uuid = "1.3.0"
serde_json = "1"

[build-dependencies]
prost-build = "0.11"

[profile.release-with-debug]
inherits = "release"
debug = true
