[package]
name = "lance-table"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Utilities for the Lance table format"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
lance-arrow.workspace = true
lance-core.workspace = true
lance-file.workspace = true
lance-io.workspace = true
arrow-array.workspace = true
arrow-buffer.workspace = true
arrow-ipc.workspace = true
arrow-schema.workspace = true
async-trait.workspace = true
aws-credential-types.workspace = true
byteorder.workspace = true
bytes.workspace = true
chrono.workspace = true
futures.workspace = true
log.workspace = true
object_store.workspace = true
prost.workspace = true
prost-types.workspace = true
rand.workspace = true
roaring.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
arrow-schema.workspace = true

[build-dependencies]
prost-build.workspace = true

[features]
dynamodb = ["aws-sdk-dynamodb"]
dynamodb_tests = ["dynamodb"]
