name: Check docs

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - docs/**

env:
  # Disable full debug symbol generation to speed up CI build and keep memory down
  # "1" means line tables only, which is useful for panic tracebacks.
  RUSTFLAGS: "-C debuginfo=1"
  # according to: https://matklad.github.io/2021/09/04/fast-rust-builds.html
  # CI builds are faster with incremental disabled.
  CARGO_INCREMENTAL: "0"

jobs:
  # Single deploy job since we're just deploying
  check-docs:
    runs-on: ubuntu-22.04-4core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: "docs/requirements.txt"
      - name: Install dependencies
        run: |
          sudo apt install -y -qq doxygen pandoc
      - name: Build python wheel
        uses: ./.github/workflows/build_linux_wheel
      - name: Build Python
        working-directory: python
        run: |
          python -m pip install $(ls target/wheels/*.whl)
          python -m pip install -r ../docs/requirements.txt
      - name: Build docs
        working-directory: docs
        run: |
          make nbconvert
          make html
      - name: Check links
        working-directory: docs
        run: |
          make linkcheck

