name: DuckDB Extension
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - integration/duckdb_lance/*
      - .github/workflows/duckdb.yml
      - ./rust/*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  Linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    defaults:
      run:
        working-directory: ./integration/duckdb_lance
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libssl-dev
      - name: Checkout submodules
        run: |
          git submodule init
          git submodule update
      - name: Make
        run: make build
      # - name: Upload Lance duckdb extension
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: duckdb-ubuntu-extension
      #     path: integration/duckdb/build/lance.duckdb_extension
      #     retention-days: 1
  MacOS:
    runs-on: macos-13
    timeout-minutes: 40
    defaults:
      run:
        working-directory: ./integration/duckdb_lance
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install protobuf
      - name: Checkout submodules
        run: |
          git submodule init
          git submodule update
      - name: Build
        run: make build
      # - name: Upload Lance duckdb extension
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: duckdb-intel-mac-extension
      #     path: integration/duckdb/build/lance.duckdb_extension
      #     retention-days: 1

